### ISSUE TITLE
Docs shortcut

### ISSUE THREAD

**Issue by AsyncBanana** [Javascripters-Development/JavaScripters-Bot#3]
Add commands to quickly search docs such as MDN. The idea is that instead of having to go outside Discord, someone helping someone else can simply run a command to generate a list of results and select the result they want. After they do so, the result will be displayed to all users with a short description (most likely from meta tags) and a link.

**Comment by MorganVonBrylan** [comment]
How the `/mdn` command currently works as of aa47f69:
1. User does the command
![1  search](https://github.com/Javascripters-Development/JavaScripters-Bot/assets/33571779/e07b1372-0c2b-4a59-a095-e8834bc0e455)
2. Bot replies with an ephemeral menu with the 10 first results (which is CSE's limit)
![2  selection](https://github.com/Javascripters-Development/JavaScripters-Bot/assets/33571779/8e013234-bc25-45bc-a252-e5d6966d62c6)
3. Bot does another reply with the excerpt of the article an an link to open it in the browser.
![3  reply](https://github.com/Javascripters-Development/JavaScripters-Bot/assets/33571779/f9ed0a5a-989a-45c1-8034-bf7378840919)

**Main flaw:** the public reply appears to other users as replying to a deleted or unreachable message, which looks weird.
![4  ugly](https://github.com/Javascripters-Development/JavaScripters-Bot/assets/33571779/f9f509a9-7af9-44c6-9970-7ce737f78f3d)
**Upside:** the select menu stays up. If it turns out the user clicked the wrong result, they can easily go and select another one (won't delete the first public reply).

Possible additions:
Searching through the Node.js docs could be nice; Bun and Deno, too. We should probably encompass all that in a `/search` command, with a subcommand for each website (`/search mdn`, `/search nodejs`, etc).
It would also allow to move `scraper.ts` to that command group's folder, decluttering the root a little.

**Comment by MorganVonBrylan** [comment]
Google's JSON Search API is being sunset.
This needs to be migrated to Vertex AI Search.

**Comment by MorganVonBrylan** [comment]
Google's JSON Search API is being sunset.
This needs to be migrated to Vertex AI Search.
